storage: ./storage

users:
  admin:
    # pinkpanther
    password: 48ded4637fe82776cfb287c623494470bea2c93b

auth:
  htpasswd:
    file: ./htpasswd
    max_users: -1

uplinks:
  npmjs:
    url: https://registry.npmjs.org/

packages:
  '@*/*':
    access: $all
    publish: $authenticated
    proxy: npmjs

  '*':
    access: $all
    publish: admin
    proxy: npmjs

logs:
  - {type: stdout, format: pretty, level: http}

listen:
  - 0.0.0.0:4873